### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by 2e0byo** [2e0byo/emacs-ng#1]
This fork is currently far from ready, but working locally.

Known bugs:

- [x] Resize handler is not called promptly on window resize.  Indeed I can't figure out what listens to resized event at all.  We probably need to register a handler.  The result is that Emacs becomes unresponsive after a resize for `0 <= t < \infinity`.  Forcing an internal redisplay by e.g. M-x (loads helm) and then sending another resize event (resizing the window twice) tends to work. *[fixed with new rendering logic]*
- [ ] Overlay windows aren't displayed properly, so they tile.  They're also useless until scaled properly.  This makes lsp-lens annoying, although I still use it by manually resizing the lens window and waiting for it to behave itself
- [ ] Segfaults on `message-box`.  (Probably a problem in upstream, but def. to fix.)
- [ ] Unable to load fonts from elisp/at runtime.
- [x] Lsp right-margin text wraps onto new line.  I *think* upgrading emacs itself will fix this. *[fixed: probably due to scaling]*
- [x] Something byte-compiled causes periodic errors.  Again, I think a problem with emacs. *[gone]*
- [ ] The xpm hack works, but for some reason doesn't resize images.  Should they be scaled like fonts? But others work fine.
- [ ] Occasional segfault which I've not tracked down (need to build emacs with debugging I think).
- [x] Automatic composite glyphs not implemented yet---we just return none rather than crashing.  [Work started] *[fixed upstream]*
- [ ] Some of the `panic()`s are reachable.  Slowly removing them.
<strike>- [ ] No menu bars (true in emacs-ng in general).  I don't use them, *but*.</strike> *[problem with window toolkit]*
- [x] LSP breadcrumbs display same size as rest of buffer.  I actually quite like this and am not sure if it's a bug, but def. wasn't the case with native emacs before. *[fixed with new scaling code]*
- [x] Not all input works correctly.  Number-pad enter sends `m` not `^m`.  [Easy to debug---just print the keyboard events] *[fixed]*

**Comment by 2e0byo** [comment]
Resize events are properly listened to (dispatched in event_loop.rs and picked up in wrterm.rs).  The mutex isn't blocking.  Adding multiple resizes doesn't fix anything.

- it is always possible to retrieve the window by switching to floating and making it much smaller
- small resizes work much better than large
- when the resize works the display briefly flickers => emacs is redrawing everything.

Therefore the error is somewhere within emacs, and we need to manually force a full frame redraw on resize for now.

**Comment by 2e0byo** [comment]
Segfaults are caused by the garbage collector trying to mark objects it shouldn't.  Why?  Why does it think the object is there at all?
